name: Learning Scanning Tools

on:
  workflow_dispatch: 

permissions:
  id-token: write
  contents: read  

jobs:
  build-and-deploy:
    name: Creating Azure Resources
    runs-on: ubuntu-latest

    steps:

      - name: Azure login
        uses: azure/login@v3
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform init
        run: terraform init
      - name: Run TFLint
        run: |
          tflint --init
          tflint

      - name: Run tfsec
        run: tfsec .

      - name: Run Gitleaks
        run: |
          gitleaks detect --source . --report-format json --report-path gitleaks-report.json

      - name: Run TruffleHog
        run: |
          trufflehog filesystem . --json   
      
         

      - name: Plan
        run: terraform plan

    
